### ISSUE TITLE
Missing requirements during installation // Wiki-Update

### ISSUE THREAD

**Issue by J-PTRson** [BuysDB/SingleCellMultiOmics#221]
Hi Buys,
I dont have a solid solution yet but I'd like to raise an issue. For SingleCellMultiOmics to work on a local machine I need to install the "bwa", "bowtie2", and samtools packages for mapping my data, but this isn't very obvious from the documentation on the github page. I can find back what went wrong from the log files and troubleshoot it, but its less than ideal. I would like to propose for me to make a "new-user-start-here" -ish  wiki page to explain the setup in more detail. That is, if you don't mind me doing so. :) 

Cheers,

**Comment by BuysDB** [comment]
Hi Joshua,
you are right, this would be very helpful!
