### ISSUE TITLE
Bam file produced by the nlaIII pipeline can't be viewed by IGV

### ISSUE THREAD

**Issue by annahyan** [BuysDB/SingleCellMultiOmics#267]
Hi,

I am using the nlaIII pipeline and I'd like to view the alignment in IGV. However, when zooming into certain genes I get 
`Error encountered querying alignments: java.lang.StringIndexOutOfBoundsException: String index out of range: 1`. 

It seems that this error is cause by certain SAM tags being overriden. 

Would you by any chance know which tags are causing the issue and how I could solve it?

Thanks

**Comment by BuysDB** [comment]
Hi annahyan, could you provide a (small) BAM file of a region where you are experiencing the issue?
Obtain it using samtools, for example if the region is on chromosome 3 between 100000-200000:
`samtools view my_alignments.bam 3:100000-200000 -o region.bam`

**Comment by annahyan** [comment]
Hi, thanks for the prompt reply. Here's a sample bam file:
https://drive.google.com/file/d/1BLEvDHsDf6OkZaQfnnZzrot128S1N1gz/view?usp=sharing

**Comment by annahyan** [comment]
okay, thanks for checking. I'm using IGV 2.16.1 on windows which I guess could explain the issue.

**Comment by annahyan** [comment]
The latest 2.17.4 version on windows worked!
