### ISSUE TITLE
How is RC tag defined?

### ISSUE THREAD

**Issue by annahyan** [BuysDB/SingleCellMultiOmics#269]
Hi,

We are trying to understand how the duplicates are handled in the pipeline and from the code it becomes clear that the decision of whether a read is a duplicate or not is based on the RC tag values  - read is a duplicate if RC is set and RC > 1. However, it is not entirely clear how the RC tag is defined and calculated. Could you please explain how it's set and what it actually means? 

Thanks

**Comment by BuysDB** [comment]
The exact implementation depends on the protocol.
The vision is that there is one original template, in SingleCellMultiomics this is a `Molecule`.
`Fragments` are reads which are evidence for this original template. The way this assignment works is dependent on the protocol. Generally a unique molecular identifier, a cut location or other genomic location and cell barcode is used to perform this assignment.
When there are multiple fragments associated with one `Molecule`, all but one fragment are flagged as duplicate. The index of the fragment within the molecule is the RC tag.

See for example for ChIC:
https://github.com/BuysDB/SingleCellMultiOmics/wiki/scCHIC-data-processing#molecule-assignment

**Comment by BuysDB** [comment]
Every unique read has the `duplicate` flag in the bam file not set, and the `read fails platform/vendor quality checks` flag not set. See https://broadinstitute.github.io/picard/explain-flags.html 
You can obtain them using `samtools view tagged.bam -F 1536`
RC is always zero for such reads, as they are the first fragment associated with the molecule, the index within the molecule is 0.

**Comment by BuysDB** [comment]
` bamTabulator.py --showtags tagged.bam` can help to figure out what information is encoded in the file.
![image](https://github.com/BuysDB/SingleCellMultiOmics/assets/24733272/c2284400-9034-4210-b093-9fb84e2ba64d)
![image](https://github.com/BuysDB/SingleCellMultiOmics/assets/24733272/2016d7f7-0eac-4603-859e-7bce011e3111)

**Comment by annahyan** [comment]
Thank you, this makes sense now!
