### ISSUE TITLE
warning in 

### ISSUE THREAD

**Issue by AnnaAntonatouPap** [BuysDB/SingleCellMultiOmics#274]
Hello,

I am using the package for my analysis inside a conda env, when I am running the bamtagmultiome.py like this inside a snakefile

` shell("bamtagmultiome.py --multiprocess --one_contig_per_process -tagthreads {threads} -introns {input.introns} -exons {input.exons} -method vasa {input.bam} -o {output.bam} > {log.stdout} 2> {log.stderr}")`

 I receive the following syntax warning :
```
/fast/home/a/aantona/miniforge3/envs/SCMO/bin/bamtagmultiome.py:560: SyntaxWarning: invalid escape sequence '\*'
  """
```

Although my pipeline is moving forward with the mapping I wonder if this error maybe is causing any problem in the data.

Thanks in advance,
Anna

**Comment by BuysDB** [comment]
Thanks for your bug report. The message is harmless, but I have fixed the issue.
Use `pip install --upgrade git+https://github.com/BuysDB/SingleCellMultiOmics.git` to install the version with the bug fixed.
