### ISSUE TITLE
Make quality plots for scChIC-seq

### ISSUE THREAD

**Issue by jakeyeung** [BuysDB/SingleCellMultiOmics#34]
Make scatterplot of RZ="TA" over total molecules.

<img width="804" alt="ta_freq" src="https://user-images.githubusercontent.com/3778225/60669408-87983080-9e6e-11e9-8922-2fa0f0018c42.png">

**Comment by BuysDB** [comment]
Scatterplot looks like this now: (Small subsampled dataset)
![ScCHICLigation](https://user-images.githubusercontent.com/24733272/60672199-0a23ee80-9e75-11e9-966f-42c88a70f765.png)
